### ISSUE TITLE
KLA files?

### ISSUE THREAD

**Issue by iandoug** [qwickly-org/Qwickly#1]
Hi

KLA files would be nice :-)

Thanks, Ian

**Comment by karmakaze** [comment]
What are KLA files?

I used Ukelele for macOS and MS Keyboard Layout Creator for Windows. Haven't done Linux yet.

I used the [Keyboard Layout Editor](http://www.keyboard-layout-editor.com) and was able to make a `Qwicker-_KFLY_.kbd.json` file.

**Comment by karmakaze** [comment]
Figured it out. It was on the keyboard analyzer site that I spent so much time on but never used the Import/Export functions.

Added the [Qwicker (KFLY)](https://github.com/qwickly-org/Qwicker/blob/master/Qwicker-KFLY.kla.json) KLA file.

also added the [Qwicker (Mod H)](https://github.com/qwickly-org/Qwicker/blob/master/Qwicker-Mod-H.kla.json) and [Qwickly (Mod B)](https://github.com/qwickly-org/Qwicker/blob/master/Qwickly-Mod-B.kla.json) KLA files.

**Comment by iandoug** [comment]
Thanks, will add to next round of testing.

**Comment by karmakaze** [comment]
> Thanks, will add to next round of testing.

Looking forward to seeing lt incorporated and how it fares among other layouts.
